dependencies:

- name: ecp-endpoint
  version: 4.16.0
  repository: https://luth2.github.io/helm-charts
  condition: ecp-endpoint.enabled

- name: ecp-directory
  version: 4.16.0
  repository: https://luth2.github.io/helm-charts
  condition: ecp-directory.enabled

- name: ecp-broker
  version: 4.16.0
  repository: https://luth2.github.io/helm-charts
  condition: ecp-broker.enabled

- name: eccosp-artemis
  version: 4.16.0
  repository: https://luth2.github.io/helm-charts
  condition: eccosp-artemis.enabled
