{{- range $instance := .Values.instance }}
{{- $name := include "ecp-endpoint.instanceName" (dict "root" $ "instance" $instance) -}}
{{- if or (not (hasKey $instance "enabled")) $instance.enabled }}
{{- $service := $instance.service | default dict -}}
{{- range $headless := list false true }}
{{- $type := ternary "ClusterIP" (default "ClusterIP" $service.type) $headless }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-{{ ternary "headless-svc" "svc" $headless }}
  labels:
    app: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
  {{- with $service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $type }}
  {{- if $headless }}
  clusterIP: None
  publishNotReadyAddresses: true
  {{- else if and (eq $type "LoadBalancer") $service.loadBalancerIP }}
  loadBalancerIP: {{ $service.loadBalancerIP | quote }}
  {{- end }}
  selector:
    app: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
  ports:
    {{- range $port := list "http" "https" "amqp" "amqps" }}
    {{- with get $service $port }}
    - name: {{ $port }}
      port: {{ .port }}
      targetPort: {{ $port }}
      protocol: TCP
      {{- if and (not $headless) (has $type (list "NodePort" "LoadBalancer")) .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}