apiVersion: v2
type: application
appVersion: "4.17.0"
kubeVersion: ">=1.28.0-0"
description: ecco-sp Helm chart for Kubernetes
name: ecco-sp
version: 5.0.0
dependencies:
  - {name: ecp-endpoint, version: 5.0.0, repository: 'file://../charts/ecp-endpoint', condition: ecp-endpoint.enabled}
  - {name: ecp-directory, version: 5.0.0, repository: 'file://../charts/ecp-directory', condition: ecp-directory.enabled}
  - {name: ecp-broker, version: 5.0.0, repository: 'file://../charts/ecp-broker', condition: ecp-broker.enabled}
  - {name: eccosp-artemis, version: 5.0.0, repository: 'file://../charts/eccosp-artemis', condition: eccosp-artemis.enabled}